/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Attribute_H_
#define	_Attribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PartialAttribute.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Attribute */
typedef PartialAttribute_t	 Attribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Attribute;
asn_struct_free_f Attribute_free;
asn_struct_print_f Attribute_print;
asn_constr_check_f Attribute_constraint;
ber_type_decoder_f Attribute_decode_ber;
der_type_encoder_f Attribute_encode_der;
xer_type_decoder_f Attribute_decode_xer;
xer_type_encoder_f Attribute_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Attribute_H_ */
#include <asn_internal.h>
