/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CompareRequest_H_
#define	_CompareRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPDN.h"
#include "AttributeValueAssertion.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CompareRequest */
typedef struct CompareRequest {
	LDAPDN_t	 entry;
	AttributeValueAssertion_t	 ava;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CompareRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompareRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _CompareRequest_H_ */
#include <asn_internal.h>
