/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LDAPString_H_
#define	_LDAPString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LDAPString */
typedef UTF8String_t	 LDAPString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDAPString;
asn_struct_free_f LDAPString_free;
asn_struct_print_f LDAPString_print;
asn_constr_check_f LDAPString_constraint;
ber_type_decoder_f LDAPString_decode_ber;
der_type_encoder_f LDAPString_encode_der;
xer_type_decoder_f LDAPString_decode_xer;
xer_type_encoder_f LDAPString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LDAPString_H_ */
#include <asn_internal.h>
