/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LDAPMessage_H_
#define	_LDAPMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageID.h"
#include "BindRequest.h"
#include "BindResponse.h"
#include "UnbindRequest.h"
#include "SearchRequest.h"
#include "SearchResultEntry.h"
#include "SearchResultDone.h"
#include "SearchResultReference.h"
#include "ModifyRequest.h"
#include "ModifyResponse.h"
#include "AddRequest.h"
#include "AddResponse.h"
#include "DelRequest.h"
#include "DelResponse.h"
#include "ModifyDNRequest.h"
#include "ModifyDNResponse.h"
#include "CompareRequest.h"
#include "CompareResponse.h"
#include "AbandonRequest.h"
#include "ExtendedRequest.h"
#include "ExtendedResponse.h"
#include "IntermediateResponse.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LDAPMessage__protocolOp_PR {
	LDAPMessage__protocolOp_PR_NOTHING,	/* No components present */
	LDAPMessage__protocolOp_PR_bindRequest,
	LDAPMessage__protocolOp_PR_bindResponse,
	LDAPMessage__protocolOp_PR_unbindRequest,
	LDAPMessage__protocolOp_PR_searchRequest,
	LDAPMessage__protocolOp_PR_searchResEntry,
	LDAPMessage__protocolOp_PR_searchResDone,
	LDAPMessage__protocolOp_PR_searchResRef,
	LDAPMessage__protocolOp_PR_modifyRequest,
	LDAPMessage__protocolOp_PR_modifyResponse,
	LDAPMessage__protocolOp_PR_addRequest,
	LDAPMessage__protocolOp_PR_addResponse,
	LDAPMessage__protocolOp_PR_delRequest,
	LDAPMessage__protocolOp_PR_delResponse,
	LDAPMessage__protocolOp_PR_modDNRequest,
	LDAPMessage__protocolOp_PR_modDNResponse,
	LDAPMessage__protocolOp_PR_compareRequest,
	LDAPMessage__protocolOp_PR_compareResponse,
	LDAPMessage__protocolOp_PR_abandonRequest,
	LDAPMessage__protocolOp_PR_extendedReq,
	LDAPMessage__protocolOp_PR_extendedResp,
	/* Extensions may appear below */
	LDAPMessage__protocolOp_PR_intermediateResponse
} LDAPMessage__protocolOp_PR;

/* Forward declarations */
struct Controls;

/* LDAPMessage */
typedef struct LDAPMessage {
	MessageID_t	 messageID;
	struct LDAPMessage__protocolOp {
		LDAPMessage__protocolOp_PR present;
		union LDAPMessage__protocolOp_u {
			BindRequest_t	 bindRequest;
			BindResponse_t	 bindResponse;
			UnbindRequest_t	 unbindRequest;
			SearchRequest_t	 searchRequest;
			SearchResultEntry_t	 searchResEntry;
			SearchResultDone_t	 searchResDone;
			SearchResultReference_t	 searchResRef;
			ModifyRequest_t	 modifyRequest;
			ModifyResponse_t	 modifyResponse;
			AddRequest_t	 addRequest;
			AddResponse_t	 addResponse;
			DelRequest_t	 delRequest;
			DelResponse_t	 delResponse;
			ModifyDNRequest_t	 modDNRequest;
			ModifyDNResponse_t	 modDNResponse;
			CompareRequest_t	 compareRequest;
			CompareResponse_t	 compareResponse;
			AbandonRequest_t	 abandonRequest;
			ExtendedRequest_t	 extendedReq;
			ExtendedResponse_t	 extendedResp;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			IntermediateResponse_t	 intermediateResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} protocolOp;
	struct Controls	*controls	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LDAPMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDAPMessage;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Controls.h"

#endif	/* _LDAPMessage_H_ */
#include <asn_internal.h>
