/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ModifyDNRequest_H_
#define	_ModifyDNRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPDN.h"
#include "RelativeLDAPDN.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ModifyDNRequest */
typedef struct ModifyDNRequest {
	LDAPDN_t	 entry;
	RelativeLDAPDN_t	 newrdn;
	BOOLEAN_t	 deleteoldrdn;
	LDAPDN_t	*newSuperior	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModifyDNRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModifyDNRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ModifyDNRequest_H_ */
#include <asn_internal.h>
