/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ModifyRequest_H_
#define	_ModifyRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDAPDN.h"
#include <asn_SEQUENCE_OF.h>
#include <ENUMERATED.h>
#include "PartialAttribute.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ModifyRequest__changes__change__operation {
	ModifyRequest__changes__change__operation_add	= 0,
	ModifyRequest__changes__change__operation_delete	= 1,
	ModifyRequest__changes__change__operation_replace	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ModifyRequest__changes__change__operation;

/* ModifyRequest */
typedef struct ModifyRequest {
	LDAPDN_t	 object;
	struct ModifyRequest__changes {
		A_SEQUENCE_OF(struct ModifyRequest__changes__change {
			ENUMERATED_t	 operation;
			PartialAttribute_t	 modification;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} changes;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ModifyRequest_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_operation_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ModifyRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _ModifyRequest_H_ */
#include <asn_internal.h>
