/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PartialAttribute_H_
#define	_PartialAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeDescription.h"
#include "AttributeValue.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PartialAttribute */
typedef struct PartialAttribute {
	AttributeDescription_t	 type;
	struct PartialAttribute__vals {
		A_SET_OF(AttributeValue_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} vals;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartialAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartialAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _PartialAttribute_H_ */
#include <asn_internal.h>
