/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#include "SubstringFilter.h"

static int
memb_substrings_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_substring_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubstringFilter__substrings__substring, choice.initial),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AssertionValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"initial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubstringFilter__substrings__substring, choice.any),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AssertionValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"any"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubstringFilter__substrings__substring, choice.final),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AssertionValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"final"
		},
};
static asn_TYPE_tag2member_t asn_MAP_substring_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initial at 225 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* any at 226 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* final at 227 */
};
static asn_CHOICE_specifics_t asn_SPC_substring_specs_4 = {
	sizeof(struct SubstringFilter__substrings__substring),
	offsetof(struct SubstringFilter__substrings__substring, _asn_ctx),
	offsetof(struct SubstringFilter__substrings__substring, present),
	sizeof(((struct SubstringFilter__substrings__substring *)0)->present),
	asn_MAP_substring_tag2el_4,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_substring_4 = {
	"CHOICE",
	"CHOICE",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_substring_4,
	3,	/* Elements count */
	&asn_SPC_substring_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_substrings_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_substring_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"substring"
		},
};
static ber_tlv_tag_t asn_DEF_substrings_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_substrings_specs_3 = {
	sizeof(struct SubstringFilter__substrings),
	offsetof(struct SubstringFilter__substrings, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_substrings_3 = {
	"substrings",
	"substrings",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_substrings_tags_3,
	sizeof(asn_DEF_substrings_tags_3)
		/sizeof(asn_DEF_substrings_tags_3[0]), /* 1 */
	asn_DEF_substrings_tags_3,	/* Same as above */
	sizeof(asn_DEF_substrings_tags_3)
		/sizeof(asn_DEF_substrings_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_substrings_3,
	1,	/* Single element */
	&asn_SPC_substrings_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SubstringFilter_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubstringFilter, type),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_AttributeDescription,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubstringFilter, substrings),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_substrings_3,
		memb_substrings_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"substrings"
		},
};
static ber_tlv_tag_t asn_DEF_SubstringFilter_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SubstringFilter_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* type at 223 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 } /* substrings at 227 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SubstringFilter_specs_1 = {
	sizeof(struct SubstringFilter),
	offsetof(struct SubstringFilter, _asn_ctx),
	asn_MAP_SubstringFilter_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SubstringFilter = {
	"SubstringFilter",
	"SubstringFilter",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SubstringFilter_tags_1,
	sizeof(asn_DEF_SubstringFilter_tags_1)
		/sizeof(asn_DEF_SubstringFilter_tags_1[0]), /* 1 */
	asn_DEF_SubstringFilter_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubstringFilter_tags_1)
		/sizeof(asn_DEF_SubstringFilter_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SubstringFilter_1,
	2,	/* Elements count */
	&asn_SPC_SubstringFilter_specs_1	/* Additional specs */
};

