/*
 * Generated by asn1c-0.9.23 (http://lionet.info/asn1c)
 * From ASN.1 module "Lightweight-Directory-Access-Protocol-V3"
 * 	found in "Lightweight-Directory-Access-Protocol-V3.asn1"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SubstringFilter_H_
#define	_SubstringFilter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeDescription.h"
#include <asn_SEQUENCE_OF.h>
#include "AssertionValue.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SubstringFilter__substrings__substring_PR {
	SubstringFilter__substrings__substring_PR_NOTHING,	/* No components present */
	SubstringFilter__substrings__substring_PR_initial,
	SubstringFilter__substrings__substring_PR_any,
	SubstringFilter__substrings__substring_PR_final,
	/* Extensions may appear below */
	
} SubstringFilter__substrings__substring_PR;

/* SubstringFilter */
typedef struct SubstringFilter {
	AttributeDescription_t	 type;
	struct SubstringFilter__substrings {
		A_SEQUENCE_OF(struct SubstringFilter__substrings__substring {
			SubstringFilter__substrings__substring_PR present;
			union SubstringFilter__substrings__substring_u {
				AssertionValue_t	 initial;
				AssertionValue_t	 any;
				AssertionValue_t	 final;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} substrings;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubstringFilter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubstringFilter;

#ifdef __cplusplus
}
#endif

#endif	/* _SubstringFilter_H_ */
#include <asn_internal.h>
